name:                Task2
version:             0.1.0.0
#bitbucket:           ""
license:             BSD3
author:              "Tomas Monkevic"
maintainer:          "tomas.monkevic97@gmail.com"
copyright:           "2018 Tomas Monkevic"

#extra-source-files:

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         No description

dependencies:
- base >= 4.7 && < 5
- text
- http-client
- bytestring
- aeson
- case-insensitive
- vector
- random
- hspec
- scotty
- transformers

library:
  source-dirs: src
  ghc-options:
    - -XOverloadedStrings

executables:
  Task2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -XOverloadedStrings
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Task2

tests:
  Task2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Task2
